package ims

import (
	"net"
	"im_go/libs/bufio"
	"im_go/libs/proto"
	"fmt"
	"io"
	"im_go/libs/define"
)

type Client struct {
	// 连接信息
	Key    	string        	//客户端连接的唯标志
	Conn   	*net.TCPConn     //连接
	reader 	*bufio.Reader	//读取
	writer 	*bufio.Writer	//输出
	pro   	*proto.Proto

	appid  int64
	uid    int64
	device_id string
	device_ID int64 //generated by device_id + platform_id

	platform_id int8

}


func NewClient(key string,conn *net.TCPConn)*Client  {
	reader := bufio.NewReaderSize(conn,int(proto.MaxPackSize))
	writer := bufio.NewWriter(conn)
	p := new(proto.Proto)
	client := &Client{
		Key:key,
		Conn:conn,
		reader:reader,
		writer:writer,
		pro:p,
	}

	return client
}

func (client *Client)read() {
	for{
		if err := client.pro.ReadTCP(client.reader);err != nil {
			if err == io.EOF {
				fmt.Println("error",err)
				break
			}
			fmt.Println("else",err)
		}else {
			client.handleMessage(*client.pro)
		}
		client.pro.Reset()
	}
	client.close()
}

func (client *Client)write() {

}


//消息处理
func (client *Client)handleMessage(pro proto.Proto)  {
	fmt.Println("操作类型",pro.Operation)
	switch pro.Operation {
	case define.OP_AUTH:
		fmt.Println(pro,string(pro.Body),pro.Operation)
	}
}


func (client *Client) AddClient() {
	route := appRoute.FindOrAddRoute(client.appid)
	route.AddClient(client)
}

func (client *Client) RemoveClient() {
	route := appRoute.FindRoute(client.appid)
	if route == nil {
		//log.Warning("can't find app route")
		return
	}
	route.RemoveClient(client)

	//if client.room_id > 0 {
	//	route.RemoveRoomClient(client.room_id, client)
	//}
}

//client 长链失败，关闭连接，处理数据保存事宜
func (client *Client)close()  {
	fmt.Println("client close",client.Key)
	client.pro = nil
	client.writer = nil
	client.reader = nil
	client.Conn.Close()
}



func (client *Client)Listen()  {
	go client.read()
	go client.write()
}


