package ims

import "net"

type Connection struct {
	conn 		*net.TCPConn
	closed 		int32

	online 		bool

	tc     		int32 //write channel timeout count


	appId     	int64
	uId       	int64
	deviceId 	string
	deviceID 	int64 //generated by device_id + platform_id

	platformId 	int8




	//ewt     chan *
}

